// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: celestial.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CelestialBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sequence uint64  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"` // Seqwuence in stream
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`          // Name of the celestial body
	Mass     float64 `protobuf:"fixed64,3,opt,name=mass,proto3" json:"mass,omitempty"`        // Mass of the celestial body
	X        float64 `protobuf:"fixed64,4,opt,name=x,proto3" json:"x,omitempty"`              // Initial x-position
	Y        float64 `protobuf:"fixed64,5,opt,name=y,proto3" json:"y,omitempty"`              // Initial y-position
	Vx       float64 `protobuf:"fixed64,6,opt,name=vx,proto3" json:"vx,omitempty"`            // Initial x-speed
	Vy       float64 `protobuf:"fixed64,7,opt,name=vy,proto3" json:"vy,omitempty"`            // Initial x-speed
}

func (x *CelestialBody) Reset() {
	*x = CelestialBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_celestial_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CelestialBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CelestialBody) ProtoMessage() {}

func (x *CelestialBody) ProtoReflect() protoreflect.Message {
	mi := &file_celestial_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CelestialBody.ProtoReflect.Descriptor instead.
func (*CelestialBody) Descriptor() ([]byte, []int) {
	return file_celestial_proto_rawDescGZIP(), []int{0}
}

func (x *CelestialBody) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *CelestialBody) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CelestialBody) GetMass() float64 {
	if x != nil {
		return x.Mass
	}
	return 0
}

func (x *CelestialBody) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CelestialBody) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *CelestialBody) GetVx() float64 {
	if x != nil {
		return x.Vx
	}
	return 0
}

func (x *CelestialBody) GetVy() float64 {
	if x != nil {
		return x.Vy
	}
	return 0
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool                      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Content map[string]*CelestialBody `protobuf:"bytes,2,rep,name=content,proto3" json:"content,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_celestial_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_celestial_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_celestial_proto_rawDescGZIP(), []int{1}
}

func (x *Data) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Data) GetContent() map[string]*CelestialBody {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_celestial_proto protoreflect.FileDescriptor

var file_celestial_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x65, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x74, 0x61, 0x69, 0x79, 0x6f, 0x75, 0x6b, 0x65, 0x69, 0x22, 0x8f, 0x01, 0x0a,
	0x0d, 0x43, 0x65, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x61, 0x6c, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6d, 0x61, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x6d, 0x61,
	0x73, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78,
	0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x0e,
	0x0a, 0x02, 0x76, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x76, 0x78, 0x12, 0x0e,
	0x0a, 0x02, 0x76, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x76, 0x79, 0x22, 0xae,
	0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x36, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x74, 0x61, 0x69, 0x79, 0x6f, 0x75, 0x6b, 0x65, 0x69, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x54, 0x0a, 0x0c, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2e, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x61, 0x69,
	0x79, 0x6f, 0x75, 0x6b, 0x65, 0x69, 0x2e, 0x43, 0x65, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x61, 0x6c,
	0x42, 0x6f, 0x64, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32,
	0x56, 0x0a, 0x10, 0x43, 0x65, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0f, 0x43, 0x65, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x61, 0x6c,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x74, 0x61, 0x69, 0x79, 0x6f, 0x75, 0x6b,
	0x65, 0x69, 0x2e, 0x43, 0x65, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x61, 0x6c, 0x42, 0x6f, 0x64, 0x79,
	0x1a, 0x0f, 0x2e, 0x74, 0x61, 0x69, 0x79, 0x6f, 0x75, 0x6b, 0x65, 0x69, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_celestial_proto_rawDescOnce sync.Once
	file_celestial_proto_rawDescData = file_celestial_proto_rawDesc
)

func file_celestial_proto_rawDescGZIP() []byte {
	file_celestial_proto_rawDescOnce.Do(func() {
		file_celestial_proto_rawDescData = protoimpl.X.CompressGZIP(file_celestial_proto_rawDescData)
	})
	return file_celestial_proto_rawDescData
}

var file_celestial_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_celestial_proto_goTypes = []interface{}{
	(*CelestialBody)(nil), // 0: taiyoukei.CelestialBody
	(*Data)(nil),          // 1: taiyoukei.Data
	nil,                   // 2: taiyoukei.Data.ContentEntry
}
var file_celestial_proto_depIdxs = []int32{
	2, // 0: taiyoukei.Data.content:type_name -> taiyoukei.Data.ContentEntry
	0, // 1: taiyoukei.Data.ContentEntry.value:type_name -> taiyoukei.CelestialBody
	0, // 2: taiyoukei.CelestialService.CelestialUpdate:input_type -> taiyoukei.CelestialBody
	1, // 3: taiyoukei.CelestialService.CelestialUpdate:output_type -> taiyoukei.Data
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_celestial_proto_init() }
func file_celestial_proto_init() {
	if File_celestial_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_celestial_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CelestialBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_celestial_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_celestial_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_celestial_proto_goTypes,
		DependencyIndexes: file_celestial_proto_depIdxs,
		MessageInfos:      file_celestial_proto_msgTypes,
	}.Build()
	File_celestial_proto = out.File
	file_celestial_proto_rawDesc = nil
	file_celestial_proto_goTypes = nil
	file_celestial_proto_depIdxs = nil
}
